# Generated by Django 3.2.4 on 2021-06-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Projects',
        ),
    ]
