# Generated by Django 3.2.4 on 2021-06-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_articles_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
